# Generated by Django 5.1.7 on 2025-03-24 13:55

from django.db import migrations, models

def create_genres(apps, schema_editor):
    Genre = apps.get_model('core', 'Genre')
    genres = [
        ('Action', 'action'),
        ('Adventure', 'adventure'),
        ('Comedy', 'comedy'),
        ('Crime', 'crime'),
        ('Drama', 'drama'),
        ('Fantasy', 'fantasy'),
        ('Historical', 'historical'),
        ('Horror', 'horror'),
        ('Science Fiction', 'scifi'),
        ('Thriller', 'thriller'),
        ('Romance', 'romance'),
        ('Documentary', 'documentary'),
        ('Animation', 'animation'),
        ('Biography', 'biography'),
        ('History', 'history'),
        ('Political', 'political'),
        ('Mystery', 'mystery'),
        ('Western', 'western'),
    ]
    for name, slug in genres:
        Genre.objects.get_or_create(name=name, slug=slug)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(create_genres)
    ]
