# Generated by Django 5.1.7 on 2025-03-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('genre', models.CharField(choices=[('ACTION', 'Action'), ('COMEDY', 'Comedy'), ('DRAMA', 'Drama'), ('HORROR', 'Horror'), ('SCIFI', 'Science Fiction'), ('THRILLER', 'Thriller'), ('ROMANCE', 'Romance'), ('DOCUMENTARY', 'Documentary'), ('ANIMATION', 'Animation'), ('FANTASY', 'Fantasy')], default='DRAMA', max_length=20)),
                ('poster', models.ImageField(upload_to='posters/')),
                ('imdb_link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
