# Generated by Django 5.1.7 on 2025-03-24 13:55

from django.db import migrations, models

def create_initial_films(apps, schema_editor):
    Film = apps.get_model('film', 'Film')
    Genre = apps.get_model('core', 'Genre')

    films = [
        {
            'title': 'The Matrix',
            'director': 'Lana Wachowski, Lilly Wachowski',
            'year': 1999,
            'description': 'A computer programmer discovers a mysterious world of digital reality.',
            'genres': ['Action', 'Science Fiction'],
            'imdb_link': 'https://www.imdb.com/title/tt0133093/',
            'poster': 'posters/the_matrix.jpg',
            'trailer_link': 'https://www.youtube.com/watch?v=vKQi3bBA1y8'
        },
        {
            'title': 'Inception',
            'director': 'Christopher Nolan',
            'year': 2010,
            'description': 'A thief who enters the dreams of others to steal secrets.',
            'genres': ['Action', 'Science Fiction', 'Thriller'],
            'imdb_link': 'https://www.imdb.com/title/tt1375666/',
            'poster': 'posters/inception.jpg',
            'trailer_link': 'https://www.youtube.com/watch?v=YoHD9XE0Gkk'
        },
        {
            'title': 'The Shawshank Redemption',
            'director': 'Frank Darabont',
            'year': 1994,
            'description': 'Two imprisoned men bond over several years, finding solace and eventual redemption through acts of common decency.',
            'genres': ['Drama'],
            'imdb_link': 'https://www.imdb.com/title/tt0111161/',
            'poster': 'posters/the_shawshank_redemption.jpg',
            'trailer_link': 'https://www.youtube.com/watch?v=6hB3S9bIaco'
        },
        {
            'title': 'The Godfather',
            'director': 'Francis Ford Coppola',
            'year': 1972,
            'description': 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.',
            'genres': ['Crime', 'Drama'],
            'imdb_link': 'https://www.imdb.com/title/tt0068646/',
            'poster': 'posters/the_godfather.jpg',
            'trailer_link': 'https://www.youtube.com/watch?v=sY1S34973zA'
        },
        {
            'title': 'The Dark Knight',
            'director': 'Christopher Nolan',
            'year': 2008,
            'description': 'When the menace known as the Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham.',
            'genres': ['Action', 'Crime', 'Drama'],
            'imdb_link': 'https://www.imdb.com/title/tt0468569/',
            'poster': 'posters/the_dark_knight.jpg',
            'trailer_link': 'https://www.youtube.com/watch?v=EXeTwQWrcCQ'
        },
        {
            'title': 'Pulp Fiction',
            'director': 'Quentin Tarantino',
            'year': 1994,
            'description': 'The lives of two mob hitmen, a boxer, a gangster\'s wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
            'genres': ['Crime', 'Drama'],
            'imdb_link': 'https://www.imdb.com/title/tt0110912/',
            'poster': 'posters/pulp_fiction.jpg',
            'trailer_link': 'https://www.youtube.com/watch?v=s7EdQ4FqbhY'
        },
        {
            'title': 'Forrest Gump',
            'director': 'Robert Zemeckis',
            'year': 1994,
            'description': 'The presidencies of Kennedy and Johnson, the Vietnam War, and other historical events unfold through the perspective of an Alabama man with an IQ of 75.',
            'genres': ['Drama', 'Romance'],
            'imdb_link': 'https://www.imdb.com/title/tt0109830/',
            'poster': 'posters/forrest_gump.jpg',
            'trailer_link': 'https://www.youtube.com/watch?v=uPIEn04Ygd8'
        },
        {
            'title': 'Fight Club',
            'director': 'David Fincher',
            'year': 1999,
            'description': 'An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into something much more.',
            'genres': ['Drama'],
            'imdb_link': 'https://www.imdb.com/title/tt0137523/',
            'poster': 'posters/fight_club.jpg',
            'trailer_link': 'https://www.youtube.com/watch?v=BdJKm16CoFc'
        },
        {
            'title': 'The Lord of the Rings: The Fellowship of the Ring',
            'director': 'Peter Jackson',
            'year': 2001,
            'description': 'A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth.',
            'genres': ['Action', 'Adventure', 'Drama'],
            'imdb_link': 'https://www.imdb.com/title/tt0120737/',
            'poster': 'posters/the_lord_of_the_rings_the_fellowship_of_the_ring.jpg',
            'trailer_link': 'https://www.youtube.com/watch?v=V75dMMIW2B4'
        },
        {
            'title': 'Star Wars: Episode V - The Empire Strikes Back',
            'director': 'Irvin Kershner',
            'year': 1980,
            'description': 'After the Rebels are brutally overpowered by the Empire, Luke Skywalker begins his training with Jedi Master Yoda.',
            'genres': ['Action', 'Adventure', 'Fantasy'],
            'imdb_link': 'https://www.imdb.com/title/tt0080684/',
            'poster': 'posters/star_wars_episode_v_the_empire_strikes_back.jpg',
            'trailer_link': 'https://www.youtube.com/watch?v=96v4Xra6Hgk'
        },
        {
            'title': 'The Silence of the Lambs',
            'director': 'Jonathan Demme',
            'year': 1991,
            'description': 'A young F.B.I. cadet must confide in an incarcerated and manipulative cannibal killer to receive his help on catching another serial killer.',
            'genres': ['Crime', 'Drama', 'Thriller'],
            'imdb_link': 'https://www.imdb.com/title/tt0102926/',
            'poster': 'posters/the_silence_of_the_lambs.jpg',
            'trailer_link': 'https://www.youtube.com/watch?v=W6Mm8WcUEe0'
        },
        {
            'title': 'Schindler\'s List',
            'director': 'Steven Spielberg',
            'year': 1993,
            'description': 'In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.',
            'genres': ['Biography', 'Drama', 'History'],
            'imdb_link': 'https://www.imdb.com/title/tt0108052/',
            'poster': 'posters/schindlers_list.jpg',
            'trailer_link': 'https://www.youtube.com/watch?v=gG22XNhtnoY'
        }
    ]

    for data in films:
        # Handle poster field separately
        poster_path = data.pop('poster', None)
        genres = data.pop('genres')

        film = Film.objects.create(
            **data,
            poster=poster_path
        )

        for genre_name in genres:
            genre = Genre.objects.get(name=genre_name)
            film.genres.add(genre)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('poster', models.ImageField(upload_to='posters/')),
                ('imdb_link', models.URLField(blank=True)),
                ('trailer_link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(to='core.genre')),
            ],
        ),
        migrations.RunPython(create_initial_films)
    ]
